name: Daily Commit

on:
  schedule:
    # Runs daily at 12:00 UTC (adjust the cron syntax as needed)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up email for commit (nitin.nitnav@gramener.com)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "nitin.nitnav@gramener.com"

      - name: Create a new commit
        run: |
          echo "Daily commit on $(date)" >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily automated commit on $(date)"
          git push
